# Created by MichaelCurrin
# https://gist.github.com/MichaelCurrin/a698731096f78240f653faf9a9127cba

name: GH Pages Deploy

on:
  push:
    branches:
      - develop
      - production

env:
  _BRANCH: ${{github.GITHUB_REF_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Setup 🛎️
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install 🔧
        run: |
        node -v
        npm install

      - name: Build 🏗️
        run: |
          echo "branch1 ${{github.ref_name}}"
          echo "Build ${{env._BRANCH}} aka ${{github.GITHUB_REF_NAME}} branch"
          npm run build:${{env._BRANCH}}

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build